# Generated by Django 3.1.5 on 2021-02-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='NAME', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(default='LOCATION', max_length=100)),
                ('is_liked', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
