# Generated by Django 3.1.5 on 2021-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
